version: '3.8'
services:
  laravel_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_siete_cuatro
    restart: always
    environment:
      DATABASE_CONNECTION: mysql
      DATABASE_HOST: mariadb_host
      DATABASE_PORT: 3306
      DATABASE_DATABASE: laravel
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www
      - ./html:/var/www/html/laravel
    networks:
      laravel_net:
        aliases:
          - laravel_host1
volumes:
  html: {}
networks:
  laravel_net:
    name: network_laravel_net
    driver: bridge